### ISSUE TITLE
Default LDAP Passwd

### ISSUE THREAD

**Issue by GeorgeGuoAT** [sepulworld/vagrant-ldap#1]
I installed a LDAP server using the repo download from this project.
but after i log into this server using vagrant ssh command,i found a passwd is need to create DN in the LDAP directory.

What is the default passwd this project set? Any reply would be appreciated.

**Comment by sepulworld** [comment]
Can you check here?

https://github.com/sepulworld/vagrant-ldap/blob/d8c6d25e1a372b3ef2875514d8c420d0c1a75718/modules/ldap/templates/client/common/nss_pam_ldap.conf.erb#L44

**Comment by GeorgeGuoAT** [comment]
Hi,Zane,thanks for your kindly reply.but actually i did not found such file "/etc/ldap.secret" in the virtual machine.
should i install a root account for the ladap service firstly?

**Comment by sepulworld** [comment]
You should probably just leverage the Puppet module that is used to create DNs.

They are created here:

https://github.com/sepulworld/vagrant-ldap/blob/master/manifests/default.pp
Add your own DN following a similar pattern in this manifest file
You can add your corresponding LDAP schema in here:
https://github.com/sepulworld/vagrant-ldap/tree/master/modules/ldap/files/schema
(see how I added and call out the brodate.schema in default.pp from here)

Then test out your changes via 

`vagrant provision`

**Comment by ghost** [comment]
the password is:test

basedn   => 'dc=brodate,dc=net',
  rootdn   => 'cn=dsadmin',
  rootpw   => 'test'

**Comment by sepulworld** [comment]
Thank you @jnuc093 

Yes, https://github.com/sepulworld/vagrant-ldap/blob/master/manifests/default.pp#L18  

Ok going to close this issue for now then.
